### ISSUE TITLE
Unable to execute the command "rails g surveyor_gui:install"

### ISSUE THREAD

**Issue by ghost** [kjayma/surveyor_gui#54]
I install "surveyor" and "protected_attributes" gems in my repo and ran migrations successfully too. However I have not been able to install and migrate "surveyor_gui". It fails with following error:

/Users/archanaraut/.rvm/gems/ruby-2.3.0/bundler/gems/surveyor_gui-a351b314e7a6/lib/surveyor_gui/models/column_methods.rb:13:in `block in <module:ColumnMethods>': uninitialized constant SurveyorGui::Models::ColumnMethods::PermittedParams (NameError)
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/activesupport-4.1.0/lib/active_support/concern.rb:120:in`class_eval'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/activesupport-4.1.0/lib/active_support/concern.rb:120:in `append_features'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/bundler/gems/surveyor_gui-a351b314e7a6/app/models/column.rb:2:in`include'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/bundler/gems/surveyor_gui-a351b314e7a6/app/models/column.rb:2:in `<class:Column>'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/bundler/gems/surveyor_gui-a351b314e7a6/app/models/column.rb:1:in`<top (required)>'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/bundler/gems/surveyor_gui-a351b314e7a6/lib/surveyor_gui/engine.rb:24:in `block (2 levels) in <class:Engine>'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/bundler/gems/surveyor_gui-a351b314e7a6/lib/surveyor_gui/engine.rb:23:in`each'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/bundler/gems/surveyor_gui-a351b314e7a6/lib/surveyor_gui/engine.rb:23:in `block in <class:Engine>'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:438:in`instance_exec'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:438:in `block in make_lambda'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:184:in`block in simple'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/activesupport-4.1.0/lib/active_support/callbacks.rb:86:in `run_callbacks'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/reloader.rb:83:in`prepare!'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/actionpack-4.1.0/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/railties-4.1.0/lib/rails/application/finisher.rb:52:in`block in module:Finisher'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in`run'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/railties-4.1.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in`block in tsort_each'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in`each_strongly_connected_component_from'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in`each'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in`each_strongly_connected_component'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in`tsort_each'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/railties-4.1.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/railties-4.1.0/lib/rails/application.rb:288:in`initialize!'
    from /Users/archanaraut/Documents/work/MyFreedomForms/config/environment.rb:5:in `<top (required)>'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:92:in`require'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:92:in `preload'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:143:in`serve'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in`loop'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
    from /Users/archanaraut/.rvm/gems/ruby-2.3.0/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in`<top (required)>'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/archanaraut/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from -e:1:in `<main>'

**Comment by ghost** [comment]
I installed surveyor and ran db migrations and then installed surveyor_gui, and then tried generating the surveyor_gui model, when I faced this issue. However following the instructions in README.md, got me out of this issue.
