### ISSUE TITLE
Install process causing "PermittedParameters" error

### ISSUE THREAD

**Issue by handlez36** [kjayma/surveyor_gui#56]
Hi, I am trying to run the 'rails g surveyor_gui:install" command. I get the following error...

/Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/surveyor_gui-9278dfff115d/app/models/permitted_params_decorator.rb:1:in `<top (required)>': uninitialized constant PermittedParams (NameError)
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/surveyor_gui-9278dfff115d/lib/surveyor_gui/engine.rb:24:in `block (2 levels) in <class:Engine>'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/surveyor_gui-9278dfff115d/lib/surveyor_gui/engine.rb:23:in `each'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/surveyor_gui-9278dfff115d/lib/surveyor_gui/engine.rb:23:in `block in <class:Engine>'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `instance_exec'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `block in make_lambda'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `call'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `block in simple'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
	from /Users/bmac/Projects/Professional/psiware/config/environment.rb:5:in `<top (required)>'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/bmac/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

I am running rails v4.2.6 and ruby v2.2.3p173. Any thoughts on what may be wrong? I have also had some issues installing 'therubyracer' via my Gemfile, so I was going to tackle that next. Would the error above have anything to do with the lack of 'therubyracer'?

Thanks in advance!

**Comment by handlez36** [comment]
Actually, just got 'therubyracer' installed finally, and I still see the same errors.
